info:
  app:
    description: Template Spring Boot API for use of CSCI 602
    name: csci-602
    version: 1.0.0
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: openapi, swagger-ui
server:
  port: 25060
  servlet:
    contextPath: /springbootapp
spring:
  application:
    name: csci-602
  datasource:
    password: AVNS_0yON0y8gf0qV0AM0lci
    url: jdbc:postgresql://csci-602-fall-2025-db-do-user-4683876-0.k.db.ondigitalocean.com:25060/mmease
    username: mmease
  mvc:
    servlet:
      load-on-startup: 1
  profiles:
    active: '@spring.profiles.active@'
springdoc:
  packagesToScan: edu.citadel.api
  pathsToMatch: /v1, /**
  show-actuator: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    edu.citadel: TRACE
